---
# Source: simple-app/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "simple-app-test-connection"
  namespace: stage
  labels:
    helm.sh/chart: simple-app-0.1.0
    app.kubernetes.io/name: simple-app
    app.kubernetes.io/instance: simple-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['simple-app:8080']
  restartPolicy: Never
