---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: simple-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: simple-app
  policy:
    semver:
      range: ">=0.2.0-0"
